# Generated by Django 2.2.5 on 2019-09-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In process'), ('done', 'Done')], default='new', max_length=40),
        ),
    ]
